# docker-compose.yml

version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=rootpassword
      - DATABASE_NAME=nestdb
    ports:
      - "3000:3000"  # Map cổng 3000 của container tới cổng 3000 của máy chủ
    depends_on:
      - db  # Đảm bảo dịch vụ MySQL đã sẵn sàng trước khi khởi động NestJS

  db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: nestdb
    ports:
      - "3306:3306"  # Map cổng 3306 của container tới cổng 3306 của máy chủ
    volumes:
      - db_data:/var/lib/mysql  # Lưu trữ dữ liệu của MySQL để giữ lại dữ liệu sau khi khởi động lại container

volumes:
  db_data:  # Volume để lưu trữ dữ liệu của MySQL
